### ISSUE TITLE
Tuple index out of range

### ISSUE THREAD

**Issue by ghost** [DIYBookScanner/spreadpi#35]
Hi guys

I keep getting the same error: Tuple index out of range. Occurs after 3-5 captures no matter what I try. It occurs both in the web interface and cli. I run Version 0.5git20150527.c802

Here's a copy paste of the error:

`spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
    capture(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 335, in capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 883, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
IndexError: tuple index out of range`

What do I do? best regards

**Comment by duerig** [comment]
Hi. Unfortunately, this is a bug in chdkptp.py. If you are using a Raspberry Pi, I have a temporary image up that has the fixed chdkptp.py. As soon as the bugfix is pulled into the main chdkptp.py repository, the fix should start appearing in the nightly builds as well.

Here is the temporary Pi image location:

http://tenrec.builders/pi/archivist-2m.zip

This is a standard Pi image with username 'pi' and password 'raspberry', but it has spreads installed as well.

**Comment by ghost** [comment]
Thank you so much duerig – I'll try it out.

**Comment by boredland** [comment]
@duerig can you post a link to the chdkptp.py issue, so I can check if that is merged?

**Comment by duerig** [comment]
Still not pulled in. I will email Johannes.

https://github.com/jbaiter/chdkptp.py/pull/3
